app = "ktlcgm"

[build]
  dockerfile = "Dockerfile.flyio"

[env]
  PORT = "8080"
  ALARM_HIGH = "on"
  ALARM_LOW = "on"
  ALARM_TIMEAGO_URGENT = "on"
  ALARM_TIMEAGO_URGENT_MINS = "30"
  ALARM_TIMEAGO_WARN = "on"
  ALARM_TIMEAGO_WARN_MINS = "15"
  ALARM_TYPES = "simple"
  ALARM_URGENT_HIGH = "on"
  ALARM_URGENT_LOW = "on"
  BG_HIGH = "260"
  BG_LOW = "55"
  BG_TARGET_BOTTOM = "80"
  BG_TARGET_TOP = "180"
  BOLUS_RENDER_OVER = "1"
  BRIDGE_PASSWORD = ""
  BRIDGE_SERVER = "US"
  BRIDGE_USER_NAME = ""
  CUSTOM_TITLE = ""
  DISPLAY_UNITS = "mmol/L"
  ENABLE = "careportal basal dbsize rawbg iob maker bridge cob bwp cage iage sage boluscalc pushover treatmentnotify mmconnect loop pump profile food openaps bage alexa override"
  MMCONNECT_PASSWORD = ""
  MMCONNECT_SERVER = "US"
  MMCONNECT_USER_NAME = ""
  NIGHT_MODE = "off"
  SHOW_PLUGINS = "careportal dbsize"
  SHOW_RAWBG = "never"
  THEME = "colors"
  TIME_FORMAT = 12

[[services]]
  internal_port = 8080
  protocol = "TCP"
  [services.port.80]
    handlers = ["http"]
  [services.port.443]
    handlers = ["tls", "http"]
