app = "ktlcgm"

[build]
  dockerfile = "Dockerfile.flyio"

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "TCP"
  [services.port.80]
    handlers = ["HTTP"]
  [services.port.443]
    handlers = ["TLS", "HTTP"]
